### ISSUE TITLE
Add files to the repo.

### ISSUE THREAD

**Issue by skorokithakis** [davidmilligan/ml-lua#1]
Hello,
could you add some files to this repository? I just installed ML on my camera yesterday and found this while looking for a way to run Lua scripts, but there's no information anywhere about how to actually install ml-lua and the scripts to my camera.

Any info in a short README would be appreciated.

**Comment by davidmilligan** [comment]
This repository only exists to host the documentation (via gh-pages). The source code is part of the main ML repository, hosted here: https://bitbucket.org/hudson/magic-lantern/branch/lua

For more information please check the forum thread: http://www.magiclantern.fm/forum/index.php?topic=14828.0

**Comment by skorokithakis** [comment]
I have looked at the thread, and couldn't find how to run the scripts. I put them in the `ml/scripts/` directory, but they don't show up in the menu. Would it be too hard to put a simple two-sentence howto in the README, rather than have people read the entire multi-page thread that's full of historical details?

**Comment by davidmilligan** [comment]
Like I said, this repo exists to host the documentation (in the gh-pages branch), of which the first sentences on the main index page should answer your question. The OP of the forum thread links to this documentation. 

Two pages is not bad and the historical details are important. It should take all of 15 minutes to read that. There are threads on the forum with hundreds of pages.

As developers who work on this project as hobby, we have limited time and resources to spend and that means documentation is not always what we would like it to be and end users must make some effort to find and figure things out on their own.

Please also consider that the Lua engine has only recently been revived and is still "under construction" so to speak.
